// <auto-generated />
using System;
using FootballProjectSoftUni.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballProjectSoftUni.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260201121741_NewFieldAndPictures")]
    partial class NewFieldAndPictures
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "600bafb9-a73d-4489-a387-643c2b8ae96c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f6f8482b-3c67-475f-9c27-eaa0923d6768",
                            Email = "admin@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Great",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@MAIL.COM",
                            NormalizedUserName = "ADMIN@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBRGz04eYo5UPlF3q63AnnpyJLGsOrQ3AedfRl4eJVfRrnFaDcYSPuNxbl9VxGB+YQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8a9e3d66-1a74-4f46-b3bf-6db333cc8e2c",
                            TwoFactorEnabled = false,
                            UserName = "admin@mail.com"
                        });
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://e-tourguide.eu/wp-content/uploads/2023/09/BL-d-scaled.jpeg",
                            Name = "Благоевград"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://www.mywanderlust.pl/wp-content/uploads/2021/07/things-to-do-in-burgas-bulgaria-138.jpg",
                            Name = "Бургас"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/e3/5b/5d/theotokos-cathedral.jpg?w=900&h=500&s=1",
                            Name = "Варна"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://freshholiday.bg/img/NOVINI/BIG_230127093507veliko-tarnovo-podmeni-ulichnoto-osvetlenie-v-chetiri-kvartala_1706007449223.jpg.webp",
                            Name = "Велико Търново"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxzE-q0_id6nvgsBF_h2zLdZ8ddlrPOC5mKw&s",
                            Name = "Видин"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvq8CUaPtVAQ8J4U4nNnfccmJ-KsHOqX5irg&s",
                            Name = "Враца"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://www.gabrovodaily.info/wp-content/uploads/2016/06/Obshtina-Gabrovo.jpg",
                            Name = "Габрово"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://bgtourism.bg/wp-content/uploads/2023/07/93DC82F8-DE23-4016-854D-02C8B622E7A7.jpeg",
                            Name = "Добрич"
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://visitkardzhali.com/wp-content/uploads/2024/11/kj1-900x500.jpg",
                            Name = "Кърджали"
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://visit-kyustendil.eu/images/kustendil-ploshtada.jpg",
                            Name = "Кюстендил"
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROnOulepJWi_vxDqO3Ma5HMQz9_Xv35UcDPg&s",
                            Name = "Ловеч"
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "https://sportenkalendar.bg/media/cache/resolve/event_medium_thumbs/uploads/pages/zheravitsa-63affff2b6dd9672914279.jpg",
                            Name = "Монтана"
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "https://cache1.24chasa.bg/Images/Cache/949/IMAGE_16373949_40_0.jpg",
                            Name = "Пазарджик"
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "https://www.pleven.bg/uploads/posts/19.jpg",
                            Name = "Плевен"
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "https://img.haskovo.net//images/news_images/2023/02/01/orig-80130789772169881.jpg?v=1675242496",
                            Name = "Перник"
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "https://img.capital.bg/shimg/zx1200y675_3964872.jpg",
                            Name = "Пловдив"
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "https://www.eufunds.bg/sites/default/files/uploads/oic/doc-icons/2020-04/Eufunds.bg%20-%20WiFi4EU%20%D0%A0%D0%B0%D0%B7%D0%B3%D1%80%D0%B0%D0%B4.jpg",
                            Name = "Разград"
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "https://faiton.bg/wp-content/uploads/2024/08/ruse-1-780x470.jpg",
                            Name = "Русе"
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "https://www.portal-silistra.eu/images/guide/2d698621d7c532d857158ecc331fb462.jpg",
                            Name = "Силистра"
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "https://new.sliven.net/res/news/316912/65920fe5e324526584fbcaa7643ff457.jpg",
                            Name = "Сливен"
                        },
                        new
                        {
                            Id = 21,
                            ImageUrl = "https://visitsmolyan.bg/wp-content/uploads/2020/10/%D0%B3%D1%80.-%D0%A1%D0%BC%D0%BE%D0%BB%D1%8F%D0%BD-%D0%BA%D0%B2.-%D0%A3%D1%81%D1%82%D0%BE%D0%B2%D0%BE-%D0%A3%D0%B8%D0%BA%D0%B8%D0%BF%D0%B5%D0%B4%D0%B8%D1%8F.jpg",
                            Name = "Смолян"
                        },
                        new
                        {
                            Id = 22,
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3NOq-4JtUcn_sFQQ9ztnTfVqfzfkNTSfG5A&s",
                            Name = "София"
                        },
                        new
                        {
                            Id = 23,
                            ImageUrl = "https://www.luximmo.bg/town-images/big/56_11.jpg",
                            Name = "Стара Загора"
                        },
                        new
                        {
                            Id = 24,
                            ImageUrl = "https://www.luximmo.bg/town-images/big/50_1.jpg",
                            Name = "Търговище"
                        },
                        new
                        {
                            Id = 25,
                            ImageUrl = "https://visithaskovo.com/wp-content/uploads/2019/09/kulacentre.jpg",
                            Name = "Хасково"
                        },
                        new
                        {
                            Id = 26,
                            ImageUrl = "https://img.capital.bg/shimg/zx1200y675_4220352.jpg",
                            Name = "Шумен"
                        },
                        new
                        {
                            Id = 27,
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0i1VLsI6GP_296dBpbHfcamtBo1OUvhxLsg&s",
                            Name = "Ямбол"
                        });
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.CityBestTeam", b =>
                {
                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("WinsInCity")
                        .HasColumnType("int");

                    b.HasKey("CityId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("CityBestTeams");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.Coach", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique()
                        .HasFilter("[TeamId] IS NOT NULL");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFromAdmin")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentMessageId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ParentMessageId");

                    b.HasIndex("UserId");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IndexInRound")
                        .HasColumnType("int");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<int?>("Team1Goals")
                        .HasColumnType("int");

                    b.Property<int?>("Team1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Team2Goals")
                        .HasColumnType("int");

                    b.Property<int?>("Team2Id")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int?>("WinnerTeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Team1Id");

                    b.HasIndex("Team2Id");

                    b.HasIndex("TournamentId");

                    b.HasIndex("WinnerTeamId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ContactMessageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ContactMessageId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.Referee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RefereedTournamentsCount")
                        .HasColumnType("int");

                    b.Property<int?>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId")
                        .IsUnique()
                        .HasFilter("[TournamentId] IS NOT NULL");

                    b.ToTable("Referees");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.RefereeComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefereeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RefereeId");

                    b.ToTable("RefereeComments");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.RefereeRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("RefereeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RefereeId", "UserId")
                        .IsUnique();

                    b.ToTable("RefereesRatings");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CoachId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("WinsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfTeams")
                        .HasColumnType("int");

                    b.Property<string>("OrganiserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ParticipationFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Prize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RefereeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Winner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganiserId");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.TournamentCity", b =>
                {
                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("CityId", "TournamentId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentsCities");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.TournamentJoinPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaidOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RefundReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefundedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeRefundId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeSessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentJoinPayments");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.TournamentParticipant", b =>
                {
                    b.Property<string>("ParticipantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParticipantId", "TournamentId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentsParticipants");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.TournamentStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("PlayersCreatedTotal")
                        .HasColumnType("int");

                    b.Property<int>("TeamsCreatedTotal")
                        .HasColumnType("int");

                    b.Property<int>("TournamentsCreatedTotal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AppStats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PlayersCreatedTotal = 0,
                            TeamsCreatedTotal = 0,
                            TournamentsCreatedTotal = 0
                        });
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.TournamentTeam", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("TeamId", "TournamentId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentsTeams");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.CityBestTeam", b =>
                {
                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.City", "City")
                        .WithMany("BestTeams")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.Team", "Team")
                        .WithMany("BestCities")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.Coach", b =>
                {
                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.Team", "Team")
                        .WithOne("Coach")
                        .HasForeignKey("FootballProjectSoftUni.Infrastructure.Data.Models.Coach", "TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.ContactMessage", b =>
                {
                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.ContactMessage", "ParentMessage")
                        .WithMany()
                        .HasForeignKey("ParentMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.Match", b =>
                {
                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.Team", "Team1")
                        .WithMany()
                        .HasForeignKey("Team1Id");

                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.Team", "Team2")
                        .WithMany()
                        .HasForeignKey("Team2Id");

                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.Team", "WinnerTeam")
                        .WithMany()
                        .HasForeignKey("WinnerTeamId");

                    b.Navigation("Team1");

                    b.Navigation("Team2");

                    b.Navigation("Tournament");

                    b.Navigation("WinnerTeam");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.Notification", b =>
                {
                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.ContactMessage", "ContactMessage")
                        .WithMany()
                        .HasForeignKey("ContactMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.Player", b =>
                {
                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.Referee", b =>
                {
                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.Tournament", "Tournament")
                        .WithOne("Referee")
                        .HasForeignKey("FootballProjectSoftUni.Infrastructure.Data.Models.Referee", "TournamentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.RefereeComment", b =>
                {
                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.Referee", "Referee")
                        .WithMany()
                        .HasForeignKey("RefereeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Referee");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.RefereeRating", b =>
                {
                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.Referee", "Referee")
                        .WithMany("Ratings")
                        .HasForeignKey("RefereeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Referee");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.Tournament", b =>
                {
                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.ApplicationUser", "Organiser")
                        .WithMany()
                        .HasForeignKey("OrganiserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organiser");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.TournamentCity", b =>
                {
                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.City", "City")
                        .WithMany("CityTournamnets")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.Tournament", "Tournament")
                        .WithMany("TournamentCities")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.TournamentJoinPayment", b =>
                {
                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.TournamentParticipant", b =>
                {
                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.ApplicationUser", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.Tournament", "Tournament")
                        .WithMany("TournamentParticipants")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.TournamentTeam", b =>
                {
                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.Team", "Team")
                        .WithMany("TeamTournaments")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.Tournament", "Tournament")
                        .WithMany("TournamentTeams")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FootballProjectSoftUni.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.City", b =>
                {
                    b.Navigation("BestTeams");

                    b.Navigation("CityTournamnets");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.Referee", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.Team", b =>
                {
                    b.Navigation("BestCities");

                    b.Navigation("Coach")
                        .IsRequired();

                    b.Navigation("Players");

                    b.Navigation("TeamTournaments");
                });

            modelBuilder.Entity("FootballProjectSoftUni.Infrastructure.Data.Models.Tournament", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Referee");

                    b.Navigation("TournamentCities");

                    b.Navigation("TournamentParticipants");

                    b.Navigation("TournamentTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
